version: '3'
services:
  franken:
    tty: true
    environment:
      CADDY_GLOBAL_OPTIONS: debug
    container_name: frankenphp-test
    image: dunglas/frankenphp
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./no-worker:/app/public
      - ./src:/app/src
      
